version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_chatbot_db
    environment:
      POSTGRES_DB: ecommerce_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ecommerce_chatbot_backend
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ecommerce_chatbot
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ecommerce_chatbot_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
